// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"ent_cassandra_sandbox/ent/migrate"

	"ent_cassandra_sandbox/ent/shoppingcart"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ShoppingCart is the client for interacting with the ShoppingCart builders.
	ShoppingCart *ShoppingCartClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ShoppingCart = NewShoppingCartClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		ShoppingCart: NewShoppingCartClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		ShoppingCart: NewShoppingCartClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ShoppingCart.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ShoppingCart.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ShoppingCart.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ShoppingCartMutation:
		return c.ShoppingCart.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ShoppingCartClient is a client for the ShoppingCart schema.
type ShoppingCartClient struct {
	config
}

// NewShoppingCartClient returns a client for the ShoppingCart from the given config.
func NewShoppingCartClient(c config) *ShoppingCartClient {
	return &ShoppingCartClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `shoppingcart.Hooks(f(g(h())))`.
func (c *ShoppingCartClient) Use(hooks ...Hook) {
	c.hooks.ShoppingCart = append(c.hooks.ShoppingCart, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `shoppingcart.Intercept(f(g(h())))`.
func (c *ShoppingCartClient) Intercept(interceptors ...Interceptor) {
	c.inters.ShoppingCart = append(c.inters.ShoppingCart, interceptors...)
}

// Create returns a builder for creating a ShoppingCart entity.
func (c *ShoppingCartClient) Create() *ShoppingCartCreate {
	mutation := newShoppingCartMutation(c.config, OpCreate)
	return &ShoppingCartCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ShoppingCart entities.
func (c *ShoppingCartClient) CreateBulk(builders ...*ShoppingCartCreate) *ShoppingCartCreateBulk {
	return &ShoppingCartCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ShoppingCartClient) MapCreateBulk(slice any, setFunc func(*ShoppingCartCreate, int)) *ShoppingCartCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ShoppingCartCreateBulk{err: fmt.Errorf("calling to ShoppingCartClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ShoppingCartCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ShoppingCartCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ShoppingCart.
func (c *ShoppingCartClient) Update() *ShoppingCartUpdate {
	mutation := newShoppingCartMutation(c.config, OpUpdate)
	return &ShoppingCartUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ShoppingCartClient) UpdateOne(sc *ShoppingCart) *ShoppingCartUpdateOne {
	mutation := newShoppingCartMutation(c.config, OpUpdateOne, withShoppingCart(sc))
	return &ShoppingCartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ShoppingCartClient) UpdateOneID(id int) *ShoppingCartUpdateOne {
	mutation := newShoppingCartMutation(c.config, OpUpdateOne, withShoppingCartID(id))
	return &ShoppingCartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ShoppingCart.
func (c *ShoppingCartClient) Delete() *ShoppingCartDelete {
	mutation := newShoppingCartMutation(c.config, OpDelete)
	return &ShoppingCartDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ShoppingCartClient) DeleteOne(sc *ShoppingCart) *ShoppingCartDeleteOne {
	return c.DeleteOneID(sc.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ShoppingCartClient) DeleteOneID(id int) *ShoppingCartDeleteOne {
	builder := c.Delete().Where(shoppingcart.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ShoppingCartDeleteOne{builder}
}

// Query returns a query builder for ShoppingCart.
func (c *ShoppingCartClient) Query() *ShoppingCartQuery {
	return &ShoppingCartQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeShoppingCart},
		inters: c.Interceptors(),
	}
}

// Get returns a ShoppingCart entity by its id.
func (c *ShoppingCartClient) Get(ctx context.Context, id int) (*ShoppingCart, error) {
	return c.Query().Where(shoppingcart.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ShoppingCartClient) GetX(ctx context.Context, id int) *ShoppingCart {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ShoppingCartClient) Hooks() []Hook {
	return c.hooks.ShoppingCart
}

// Interceptors returns the client interceptors.
func (c *ShoppingCartClient) Interceptors() []Interceptor {
	return c.inters.ShoppingCart
}

func (c *ShoppingCartClient) mutate(ctx context.Context, m *ShoppingCartMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ShoppingCartCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ShoppingCartUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ShoppingCartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ShoppingCartDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ShoppingCart mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ShoppingCart []ent.Hook
	}
	inters struct {
		ShoppingCart []ent.Interceptor
	}
)
