// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ent_cassandra_sandbox/ent/schema"
	"ent_cassandra_sandbox/ent/shoppingcart"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	shoppingcartFields := schema.ShoppingCart{}.Fields()
	_ = shoppingcartFields
	// shoppingcartDescItemCount is the schema descriptor for item_count field.
	shoppingcartDescItemCount := shoppingcartFields[1].Descriptor()
	// shoppingcart.DefaultItemCount holds the default value on creation for the item_count field.
	shoppingcart.DefaultItemCount = shoppingcartDescItemCount.Default.(int)
	// shoppingcartDescLastUpdateTimestamp is the schema descriptor for last_update_timestamp field.
	shoppingcartDescLastUpdateTimestamp := shoppingcartFields[2].Descriptor()
	// shoppingcart.DefaultLastUpdateTimestamp holds the default value on creation for the last_update_timestamp field.
	shoppingcart.DefaultLastUpdateTimestamp = shoppingcartDescLastUpdateTimestamp.Default.(func() time.Time)
	// shoppingcart.UpdateDefaultLastUpdateTimestamp holds the default value on update for the last_update_timestamp field.
	shoppingcart.UpdateDefaultLastUpdateTimestamp = shoppingcartDescLastUpdateTimestamp.UpdateDefault.(func() time.Time)
}
