// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ent_cassandra_sandbox/ent/predicate"
	"ent_cassandra_sandbox/ent/shoppingcart"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShoppingCartDelete is the builder for deleting a ShoppingCart entity.
type ShoppingCartDelete struct {
	config
	hooks    []Hook
	mutation *ShoppingCartMutation
}

// Where appends a list predicates to the ShoppingCartDelete builder.
func (scd *ShoppingCartDelete) Where(ps ...predicate.ShoppingCart) *ShoppingCartDelete {
	scd.mutation.Where(ps...)
	return scd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (scd *ShoppingCartDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, scd.sqlExec, scd.mutation, scd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (scd *ShoppingCartDelete) ExecX(ctx context.Context) int {
	n, err := scd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (scd *ShoppingCartDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shoppingcart.Table, sqlgraph.NewFieldSpec(shoppingcart.FieldID, field.TypeInt))
	if ps := scd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, scd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	scd.mutation.done = true
	return affected, err
}

// ShoppingCartDeleteOne is the builder for deleting a single ShoppingCart entity.
type ShoppingCartDeleteOne struct {
	scd *ShoppingCartDelete
}

// Where appends a list predicates to the ShoppingCartDelete builder.
func (scdo *ShoppingCartDeleteOne) Where(ps ...predicate.ShoppingCart) *ShoppingCartDeleteOne {
	scdo.scd.mutation.Where(ps...)
	return scdo
}

// Exec executes the deletion query.
func (scdo *ShoppingCartDeleteOne) Exec(ctx context.Context) error {
	n, err := scdo.scd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shoppingcart.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (scdo *ShoppingCartDeleteOne) ExecX(ctx context.Context) {
	if err := scdo.Exec(ctx); err != nil {
		panic(err)
	}
}
