// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ShoppingCart is the predicate function for shoppingcart builders.
type ShoppingCart func(*sql.Selector)
